name: Quark
description: $description
version: '$version'

main: spout.plugin.quark.QuarkPlugin
bootstrapper: spout.plugin.quark.QuarkPluginBootstrap
api-version: '26.1.2'
load: POSTWORLD
namespaces:
  quark: Quark

authors:
  - Violet Moon
  - Martijn Muijsers
website: https://github.com/ModernSpout/Quark-plugin
